"""Audit Layer 2 scores for items below the threshold that are missing rationale comments.

The rubric guidance (eval-harness-reference.md) states: *"Scores below 0.7 should
have a comment."*  This script reads human scores from Langfuse and flags any score
below ``--threshold`` (default 0.7) whose comment field is empty or only whitespace.

Produces a summary to stdout and optionally writes a markdown report.

Usage (repo root, venv active)::

    python scripts/audit_layer2_comments.py \\
        --dataset-name "LaborPulse Golden Questions" \\
        --run-name v1-baseline

    python scripts/audit_layer2_comments.py \\
        --run-name v1-baseline \\
        --threshold 0.7 \\
        --output eval/qa_layer2_comment_audit.md
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path
from typing import Any

_REPO_ROOT = Path(__file__).resolve().parent.parent
if str(_REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(_REPO_ROOT))

from dotenv import load_dotenv  # noqa: E402

load_dotenv(_REPO_ROOT / ".env")

import structlog  # noqa: E402

from eval.qa_scoring import LAYER2_METRIC_NAMES  # noqa: E402

log = structlog.get_logger()

_DEFAULT_DATASET = "LaborPulse Golden Questions"
_DEFAULT_THRESHOLD = 0.7


def _fetch_human_scores_flat(
    lf: Any,
    dataset_name: str,
    run_name: str,
) -> list[dict[str, Any]]:
    """Fetch all human Layer 2 scores across all traces in the run.

    Returns a flat list of score dicts: trace_id, gq_id, name, value, comment, author.
    """
    run = lf.get_dataset_run(dataset_name=dataset_name, dataset_run_name=run_name)
    flat: list[dict[str, Any]] = []
    for item in run.dataset_run_items:
        trace_id = str(item.trace_id or "")
        dataset_item_id = str(getattr(item, "dataset_item_id", "") or "")
        if not trace_id:
            continue
        resp = lf.fetch_scores(trace_id=trace_id)
        scores = resp.data if hasattr(resp, "data") else resp
        for s in scores:
            name = str(getattr(s, "name", None) or "")
            if name not in LAYER2_METRIC_NAMES:
                continue
            val = getattr(s, "value", None)
            comment = str(getattr(s, "comment", None) or "").strip()
            author = str(getattr(s, "author_user_id", None) or "")
            source = str(getattr(s, "source", "") or "").upper()
            flat.append(
                {
                    "trace_id": trace_id,
                    "dataset_item_id": dataset_item_id,
                    "name": name,
                    "value": float(val) if isinstance(val, (int, float)) else None,
                    "comment": comment,
                    "author": author,
                    "source": source,
                }
            )
    return flat


def _find_violations(
    scores: list[dict[str, Any]],
    threshold: float,
) -> list[dict[str, Any]]:
    """Return scores below threshold whose comment is empty."""
    return [s for s in scores if s["value"] is not None and s["value"] < threshold and not s["comment"]]


def _render_audit_report(
    run_name: str,
    all_scores: list[dict[str, Any]],
    violations: list[dict[str, Any]],
    threshold: float,
) -> str:
    total = len(all_scores)
    below = sum(1 for s in all_scores if s["value"] is not None and s["value"] < threshold)
    viol_n = len(violations)

    lines = [
        f"# Layer 2 Comment Audit — run: `{run_name}`",
        "",
        "Generated by `scripts/audit_layer2_comments.py`.",
        "",
        "## Summary",
        "",
        f"- Total human scores found: **{total}**",
        f"- Scores below {threshold}: **{below}**",
        f"- Scores below {threshold} *without* a comment: **{viol_n}** {'✓ none' if viol_n == 0 else '← requires action'}",
        "",
    ]

    if viol_n == 0:
        lines += [
            "All low scores have rationale comments. No action required.",
            "",
        ]
    else:
        lines += [
            f"## {viol_n} score(s) requiring a comment",
            "",
            "Each annotator should add a comment explaining why the score is below the threshold.",
            "",
            "| Metric | Value | Author | trace_id |",
            "|--------|-------|--------|---------|",
        ]
        for v in sorted(violations, key=lambda x: (x["name"], x["value"] or 0)):
            lines.append(
                f"| {v['name']} | {v['value']:.3f} | {v['author'] or '(unknown)'} | `{v['trace_id'][:16]}...` |"
            )
        lines += [
            "",
            "To add a comment: open the trace in Langfuse → click the score → edit the comment field.",
            "",
        ]

    # Per-metric breakdown
    lines += ["## Per-metric breakdown", ""]
    for metric in sorted(LAYER2_METRIC_NAMES):
        metric_scores = [s for s in all_scores if s["name"] == metric]
        n_metric = len(metric_scores)
        below_metric = [s for s in metric_scores if s["value"] is not None and s["value"] < threshold]
        no_comment = [s for s in below_metric if not s["comment"]]
        mean_val = sum(s["value"] for s in metric_scores if s["value"] is not None) / n_metric if n_metric else None
        lines += [
            f"### {metric}",
            f"- Total scores: {n_metric}",
            f"- Mean: {mean_val:.3f}" if mean_val is not None else "- Mean: n/a",
            f"- Below {threshold}: {len(below_metric)}",
            f"- Missing comment: {len(no_comment)}",
            "",
        ]

    return "\n".join(lines)


def main(argv: list[str] | None = None) -> int:
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument("--dataset-name", default=_DEFAULT_DATASET, help="Langfuse dataset name")
    p.add_argument("--run-name", required=True, help="Langfuse dataset run name (e.g. v1-baseline)")
    p.add_argument(
        "--threshold",
        type=float,
        default=_DEFAULT_THRESHOLD,
        help=f"Score threshold below which a comment is required (default: {_DEFAULT_THRESHOLD})",
    )
    p.add_argument(
        "--output",
        type=Path,
        default=None,
        help="Write markdown audit report to this path (default: stdout only)",
    )
    args = p.parse_args(argv)

    from langfuse import Langfuse

    lf = Langfuse()

    log.info("fetching_human_scores", run_name=args.run_name, dataset_name=args.dataset_name)
    try:
        scores = _fetch_human_scores_flat(lf, args.dataset_name, args.run_name)
    except Exception as exc:  # noqa: BLE001
        log.error("fetch_failed", error=str(exc))
        lf.shutdown()
        return 1
    finally:
        lf.flush()
        lf.shutdown()

    if not scores:
        print("No Layer 2 human scores found. Humans must score in the Langfuse UI first.", file=sys.stderr)
        return 0

    violations = _find_violations(scores, args.threshold)

    report = _render_audit_report(args.run_name, scores, violations, args.threshold)

    if args.output:
        args.output.parent.mkdir(parents=True, exist_ok=True)
        args.output.write_text(report, encoding="utf-8")
        print(f"Wrote {args.output}")

    # Always print a console summary
    total = len(scores)
    below = sum(1 for s in scores if s["value"] is not None and s["value"] < args.threshold)
    print(f"\nRun: {args.run_name}  threshold: {args.threshold}")
    print(f"Total Layer 2 scores: {total}  below threshold: {below}  missing comment: {len(violations)}")
    if violations:
        print(f"\n{len(violations)} score(s) need a rationale comment:")
        for v in violations[:10]:
            print(f"  {v['name']}={v['value']:.3f}  author={v['author'] or '(unknown)'}  trace={v['trace_id'][:24]}")
        if len(violations) > 10:
            print(f"  ... and {len(violations) - 10} more. Use --output for the full list.")
        return 1  # Non-zero exit signals CI that action is required

    print("All low scores have rationale comments.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
